# Generated by Django 3.0.3 on 2020-05-02 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='All_students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_short', models.CharField(max_length=50)),
                ('course_full', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registered_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_course_full', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_name', to='elearn.Course')),
                ('reg_course_short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_code', to='elearn.Course')),
                ('reg_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nos', to='elearn.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
