# Generated by Django 3.0.3 on 2020-05-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_students',
            old_name='matric_number',
            new_name='matric',
        ),
    ]
