# Generated by Django 3.0.3 on 2020-05-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0002_auto_20200502_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_students',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
