# Generated by Django 3.0.3 on 2020-05-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0004_remove_all_students_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_course',
            name='reg_course_full',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registered_course',
            name='reg_course_short',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registered_course',
            name='reg_unit',
            field=models.CharField(max_length=50),
        ),
    ]
