# Generated by Django 3.0.3 on 2020-05-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0007_auto_20200503_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.IntegerField(default='3000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registered_course',
            name='cost',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
    ]
