# Generated by Django 3.0.3 on 2020-05-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0012_personal_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='title',
            field=models.CharField(default='New Message', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='title',
            field=models.CharField(default='New message', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personal',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
