# Generated by Django 3.0.3 on 2020-05-03 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
