# Generated by Django 3.0.3 on 2020-05-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200503_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='matric_number',
            field=models.CharField(max_length=50),
        ),
    ]
