# Generated by Django 3.0.3 on 2020-05-03 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0002_auto_20200502_2306'),
        ('user', '0007_auto_20200503_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='matric_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.All_students'),
        ),
    ]
