# Generated by Django 3.0.3 on 2020-05-03 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0003_all_students_registered'),
        ('user', '0008_auto_20200503_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='matric_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='student_info',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='elearn.All_students'),
            preserve_default=False,
        ),
    ]
