# Generated by Django 3.0.3 on 2020-05-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200503_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student_info',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='matric_number',
            field=models.CharField(default='False', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
